CREATE TABLE citas(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
fecha DATE NOT NULL,
paciente VARCHAR(100) NOT NULL,
doctorId BIGINT NOT NULL,
estado VARCHAR(100) NOT NULL,
notas VARCHAR(500),
hora TIME NOT NULL
)